import { FretMap, JamTrack, Mode, ModeMap, NoteSymbol } from '../../util/types';

export const cIonianMode: ModeMap = [
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const dDorianMode: ModeMap = [
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const dHarmonicMinor: ModeMap = [
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const cHarmonicMinor: ModeMap = [
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const fSharpHarmonicMinor: ModeMap = [
  {
    name: 'f',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const cPhrygianMode: ModeMap = [
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const bFlatPhrygian: ModeMap = [
  {
    name: 'b',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const aFlatPhrygian: ModeMap = [
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: true,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const bFlatLocrian: ModeMap = [
  {
    name: 'b',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const aSharpMajor: ModeMap = [
  {
    name: 'a',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: true,
  },
  {
    name: 'd',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: true,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: true,
  },
];

export const cIonianFretMappings: FretMap = [
  { string: 'A', fret: 0, displayName: 'A', degree: 'submediant' },
  { string: 'A', fret: 2, displayName: 'B', degree: 'leadingTone' },
  { string: 'A', fret: 3, displayName: 'C', degree: 'tonic' },
  { string: 'A', fret: 5, displayName: 'D', degree: 'supertonic' },
  { string: 'A', fret: 7, displayName: 'E', degree: 'mediant' },
  { string: 'A', fret: 8, displayName: 'F', degree: 'subdominant' },
  { string: 'A', fret: 10, displayName: 'G', degree: 'dominant' },
  { string: 'A', fret: 12, displayName: 'A', degree: 'submediant' },
  { string: 'B', fret: 0, displayName: 'B', degree: 'leadingTone' },
  { string: 'B', fret: 1, displayName: 'C', degree: 'tonic' },
  { string: 'B', fret: 3, displayName: 'D', degree: 'supertonic' },
  { string: 'B', fret: 5, displayName: 'E', degree: 'mediant' },
  { string: 'B', fret: 6, displayName: 'F', degree: 'subdominant' },
  { string: 'B', fret: 8, displayName: 'G', degree: 'dominant' },
  { string: 'B', fret: 10, displayName: 'A', degree: 'submediant' },
  { string: 'B', fret: 12, displayName: 'B', degree: 'leadingTone' },
  { string: 'D', fret: 0, displayName: 'D', degree: 'supertonic' },
  { string: 'D', fret: 2, displayName: 'E', degree: 'mediant' },
  { string: 'D', fret: 3, displayName: 'F', degree: 'subdominant' },
  { string: 'D', fret: 5, displayName: 'G', degree: 'dominant' },
  { string: 'D', fret: 7, displayName: 'A', degree: 'submediant' },
  { string: 'D', fret: 9, displayName: 'B', degree: 'leadingTone' },
  { string: 'D', fret: 10, displayName: 'C', degree: 'tonic' },
  { string: 'D', fret: 12, displayName: 'D', degree: 'supertonic' },
  { string: 'E', fret: 0, displayName: 'E', degree: 'mediant' },
  { string: 'E', fret: 1, displayName: 'F', degree: 'subdominant' },
  { string: 'E', fret: 3, displayName: 'G', degree: 'dominant' },
  { string: 'E', fret: 5, displayName: 'A', degree: 'submediant' },
  { string: 'E', fret: 7, displayName: 'B', degree: 'leadingTone' },
  { string: 'E', fret: 8, displayName: 'C', degree: 'tonic' },
  { string: 'E', fret: 10, displayName: 'D', degree: 'supertonic' },
  { string: 'E', fret: 12, displayName: 'E', degree: 'mediant' },
  { string: 'G', fret: 0, displayName: 'G', degree: 'dominant' },
  { string: 'G', fret: 2, displayName: 'A', degree: 'submediant' },
  { string: 'G', fret: 4, displayName: 'B', degree: 'leadingTone' },
  { string: 'G', fret: 5, displayName: 'C', degree: 'tonic' },
  { string: 'G', fret: 7, displayName: 'D', degree: 'supertonic' },
  { string: 'G', fret: 9, displayName: 'E', degree: 'mediant' },
  { string: 'G', fret: 10, displayName: 'F', degree: 'subdominant' },
  { string: 'G', fret: 12, displayName: 'G', degree: 'dominant' },
];

export const dIonianFretMappings: FretMap = [
  { string: 'A', fret: 0, displayName: 'A', degree: 'dominant' },
  { string: 'A', fret: 2, displayName: 'B', degree: 'submediant' },
  { string: 'A', fret: 4, displayName: 'C#', degree: 'leadingTone' },
  { string: 'A', fret: 5, displayName: 'D', degree: 'tonic' },
  { string: 'A', fret: 7, displayName: 'E', degree: 'supertonic' },
  { string: 'A', fret: 9, displayName: 'F#', degree: 'mediant' },
  { string: 'A', fret: 10, displayName: 'G', degree: 'subdominant' },
  { string: 'A', fret: 12, displayName: 'A', degree: 'dominant' },
  { string: 'B', fret: 0, displayName: 'B', degree: 'submediant' },
  { string: 'B', fret: 2, displayName: 'C#', degree: 'leadingTone' },
  { string: 'B', fret: 3, displayName: 'D', degree: 'tonic' },
  { string: 'B', fret: 5, displayName: 'E', degree: 'supertonic' },
  { string: 'B', fret: 7, displayName: 'F#', degree: 'mediant' },
  { string: 'B', fret: 8, displayName: 'G', degree: 'subdominant' },
  { string: 'B', fret: 10, displayName: 'A', degree: 'dominant' },
  { string: 'B', fret: 12, displayName: 'B', degree: 'submediant' },
  { string: 'D', fret: 0, displayName: 'D', degree: 'tonic' },
  { string: 'D', fret: 2, displayName: 'E', degree: 'supertonic' },
  { string: 'D', fret: 4, displayName: 'F#', degree: 'mediant' },
  { string: 'D', fret: 5, displayName: 'G', degree: 'subdominant' },
  { string: 'D', fret: 7, displayName: 'A', degree: 'dominant' },
  { string: 'D', fret: 9, displayName: 'B', degree: 'submediant' },
  { string: 'D', fret: 11, displayName: 'C#', degree: 'leadingTone' },
  { string: 'D', fret: 12, displayName: 'D', degree: 'tonic' },
  { string: 'E', fret: 0, displayName: 'E', degree: 'supertonic' },
  { string: 'E', fret: 2, displayName: 'F#', degree: 'mediant' },
  { string: 'E', fret: 3, displayName: 'G', degree: 'subdominant' },
  { string: 'E', fret: 5, displayName: 'A', degree: 'dominant' },
  { string: 'E', fret: 7, displayName: 'B', degree: 'submediant' },
  { string: 'E', fret: 9, displayName: 'C#', degree: 'leadingTone' },
  { string: 'E', fret: 10, displayName: 'D', degree: 'tonic' },
  { string: 'E', fret: 12, displayName: 'E', degree: 'supertonic' },
  { string: 'G', fret: 0, displayName: 'G', degree: 'subdominant' },
  { string: 'G', fret: 2, displayName: 'A', degree: 'dominant' },
  { string: 'G', fret: 4, displayName: 'B', degree: 'submediant' },
  { string: 'G', fret: 6, displayName: 'C#', degree: 'leadingTone' },
  { string: 'G', fret: 7, displayName: 'D', degree: 'tonic' },
  { string: 'G', fret: 9, displayName: 'E', degree: 'supertonic' },
  { string: 'G', fret: 11, displayName: 'F#', degree: 'mediant' },
  { string: 'G', fret: 12, displayName: 'G', degree: 'subdominant' },
];

export const cIonianJamTrack: JamTrack = {
  key: NoteSymbol.c,
  mode: Mode.ionian,
  youTubeId: 'test123',
  title: 'C Ionian Jam Track',
  creator: 'Guitar Whizz'
};
