import { GenerateFretMapService } from './generate-fret-map.service';

export const GenerateFretMapServiceMock: GenerateFretMapService = {
  isNatural: jest.fn(),
  isSharp: jest.fn(),
  isFlat: jest.fn(),
  isDoubleFlat: jest.fn(),
  isDoubleSharp: jest.fn(),
  generateNextNote: jest.fn(),
  generateMode: jest.fn(),
  convertNoteObjectToHumanReadable: jest.fn(),
  convertNoteToFretMapKey: jest.fn(),
  getFretMapping: jest.fn(),
  sortFretMapping: jest.fn(),
};

export const cIonianMode = [
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const dDorianMode = [
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const dHarmonicMinor = [
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const cHarmonicMinor = [
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const fSharpHarmonicMinor = [
  {
    name: 'f',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const cPhrygianMode = [
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const bFlatPhrygian = [
  {
    name: 'b',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const aFlatPhrygian = [
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: false,
    flat: false,
    doubleFlat: true,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const bFlatLocrian = [
  {
    name: 'b',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'd',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'g',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'a',
    sharp: false,
    flat: true,
    doubleFlat: false,
    doubleSharp: false,
  },
];

export const aSharpMajor = [
  {
    name: 'a',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'b',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'c',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: true,
  },
  {
    name: 'd',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'e',
    sharp: true,
    flat: false,
    doubleFlat: false,
    doubleSharp: false,
  },
  {
    name: 'f',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: true,
  },
  {
    name: 'g',
    sharp: false,
    flat: false,
    doubleFlat: false,
    doubleSharp: true,
  },
];

export const cIonianFretMappings = [
  { string: 'A', fret: 0, displayName: 'A' },
  { string: 'A', fret: 2, displayName: 'B' },
  { string: 'A', fret: 3, displayName: 'C' },
  { string: 'A', fret: 5, displayName: 'D' },
  { string: 'A', fret: 7, displayName: 'E' },
  { string: 'A', fret: 8, displayName: 'F' },
  { string: 'A', fret: 10, displayName: 'G' },
  { string: 'A', fret: 12, displayName: 'A' },
  { string: 'B', fret: 0, displayName: 'B' },
  { string: 'B', fret: 1, displayName: 'C' },
  { string: 'B', fret: 3, displayName: 'D' },
  { string: 'B', fret: 5, displayName: 'E' },
  { string: 'B', fret: 6, displayName: 'F' },
  { string: 'B', fret: 8, displayName: 'G' },
  { string: 'B', fret: 10, displayName: 'A' },
  { string: 'B', fret: 12, displayName: 'B' },
  { string: 'D', fret: 0, displayName: 'D' },
  { string: 'D', fret: 2, displayName: 'E' },
  { string: 'D', fret: 3, displayName: 'F' },
  { string: 'D', fret: 5, displayName: 'G' },
  { string: 'D', fret: 7, displayName: 'A' },
  { string: 'D', fret: 9, displayName: 'B' },
  { string: 'D', fret: 10, displayName: 'C' },
  { string: 'D', fret: 12, displayName: 'D' },
  { string: 'E', fret: 0, displayName: 'E' },
  { string: 'E', fret: 1, displayName: 'F' },
  { string: 'E', fret: 3, displayName: 'G' },
  { string: 'E', fret: 5, displayName: 'A' },
  { string: 'E', fret: 7, displayName: 'B' },
  { string: 'E', fret: 8, displayName: 'C' },
  { string: 'E', fret: 10, displayName: 'D' },
  { string: 'E', fret: 12, displayName: 'E' },
  { string: 'G', fret: 0, displayName: 'G' },
  { string: 'G', fret: 2, displayName: 'A' },
  { string: 'G', fret: 4, displayName: 'B' },
  { string: 'G', fret: 5, displayName: 'C' },
  { string: 'G', fret: 7, displayName: 'D' },
  { string: 'G', fret: 9, displayName: 'E' },
  { string: 'G', fret: 10, displayName: 'F' },
  { string: 'G', fret: 12, displayName: 'G' },
];

export const dIonianFretMappings = [
  { string: 'A', fret: 0, displayName: 'A' },
  { string: 'A', fret: 2, displayName: 'B' },
  { string: 'A', fret: 4, displayName: 'C#' },
  { string: 'A', fret: 5, displayName: 'D' },
  { string: 'A', fret: 7, displayName: 'E' },
  { string: 'A', fret: 9, displayName: 'F#' },
  { string: 'A', fret: 10, displayName: 'G' },
  { string: 'A', fret: 12, displayName: 'A' },
  { string: 'B', fret: 0, displayName: 'B' },
  { string: 'B', fret: 2, displayName: 'C#' },
  { string: 'B', fret: 3, displayName: 'D' },
  { string: 'B', fret: 5, displayName: 'E' },
  { string: 'B', fret: 7, displayName: 'F#' },
  { string: 'B', fret: 8, displayName: 'G' },
  { string: 'B', fret: 10, displayName: 'A' },
  { string: 'B', fret: 12, displayName: 'B' },
  { string: 'D', fret: 0, displayName: 'D' },
  { string: 'D', fret: 2, displayName: 'E' },
  { string: 'D', fret: 4, displayName: 'F#' },
  { string: 'D', fret: 5, displayName: 'G' },
  { string: 'D', fret: 7, displayName: 'A' },
  { string: 'D', fret: 9, displayName: 'B' },
  { string: 'D', fret: 11, displayName: 'C#' },
  { string: 'D', fret: 12, displayName: 'D' },
  { string: 'E', fret: 0, displayName: 'E' },
  { string: 'E', fret: 2, displayName: 'F#' },
  { string: 'E', fret: 3, displayName: 'G' },
  { string: 'E', fret: 5, displayName: 'A' },
  { string: 'E', fret: 7, displayName: 'B' },
  { string: 'E', fret: 9, displayName: 'C#' },
  { string: 'E', fret: 10, displayName: 'D' },
  { string: 'E', fret: 12, displayName: 'E' },
  { string: 'G', fret: 0, displayName: 'G' },
  { string: 'G', fret: 2, displayName: 'A' },
  { string: 'G', fret: 4, displayName: 'B' },
  { string: 'G', fret: 6, displayName: 'C#' },
  { string: 'G', fret: 7, displayName: 'D' },
  { string: 'G', fret: 9, displayName: 'E' },
  { string: 'G', fret: 11, displayName: 'F#' },
  { string: 'G', fret: 12, displayName: 'G' },
];
